FROM php:8.2-cli

WORKDIR /app

# install dependency
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    curl \
    libpq-dev

# install PHP extensions
RUN docker-php-ext-install pdo pdo_pgsql

# install Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs

# install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# copy project
COPY . .

# install PHP dependencies
RUN composer install --no-dev --optimize-autoloader

# install frontend dependencies
RUN npm install

# build tailwind + shadcn assets
RUN npm run build

# expose port
EXPOSE 10000

# start laravel
CMD php artisan serve --host=0.0.0.0 --port=10000
